### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by mwarning** [SAWARATSUKI/KawaiiLogos#121]
Hi,

is it OK to use the logos as [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/)? It seems to match your intention of the propretary license the most and something well known and unterstood.

I would also like to put them into this sticker box of mine: https://mwarning.github.io/chaos-sticker-collection/

best,
mwarning

**Comment by kamikyoku** [comment]
Unless stated, the logos are still under the license put by the creator of the work.

**Comment by mwarning** [comment]
@kamikyoku I understand. The original Logo is under the license. But I also understand that you are fine with CC BY-NC-SA for your part.
