### ISSUE TITLE
[Request] Visual Studio Code

### ISSUE THREAD

**Issue by DongZhaoXiong** [SAWARATSUKI/KawaiiLogos#13]

**Comment by kamikyoku** [comment]
Visual Studio Code logo already exists.

**Comment by DongZhaoXiong** [comment]
> Visual Studio Code logo already exists.

Okay, but I can not find this logo

**Comment by kamikyoku** [comment]
The logo repo was privated. There's https://vtuber-style-logos.vercel.app/, if you want.

**Comment by DongZhaoXiong** [comment]
> The logo repo was privated. There's still https://vtuber-style-logos.vercel.app/, if you want the logo.

Oh, many thanks!

**Comment by nishiiko** [comment]
@DongZhaoXiong just a reminder to close this issue...

**Comment by qwertyuiopr** [comment]
@DongZhaoXiong Just a reminder to close the issue...

**Comment by clarmso** [comment]
Here's the logo.
https://twitter.com/sawaratsuki1004/status/1784219617839456403

**Comment by G3NSVRV** [comment]
Hey, what happened to this logo? It was on the original repo, but now is gone:

https://github.com/SAWARATSUKI/ServiceLogos

https://x.com/sawaratsuki1004/status/1784219617839456403?s=46
