### ISSUE TITLE
[Request] Rust

### ISSUE THREAD

**Issue by blyxyas** [SAWARATSUKI/KawaiiLogos#167]
### Duplicate Check

- [X] Checked

### Logo Category

Service

### Logo Name

Rust

### Logo Name (Japanese)

Rust

### Service URL

https://github.com/rust-lang/rust

### Permission

Yes

### Contact Information

https://tech.lgbt/@blyxyas blyxyas@gmail.com

### Comments or Additional Information

![image](https://github.com/user-attachments/assets/bb1b24af-80be-4e89-a1f9-6688689b2db4)

**Comment by SAWARATSUKI** [comment]
@blyxyas 
Hi there, I'm a newbie to the site and I've been trying to get back to you! Sorry for the delay!
Am I correct in assuming that Rust officials have given you permission to create a logo? （I just want to make sure 🫠 )

**Comment by SAWARATSUKI** [comment]
Published!

**Comment by SAWARATSUKI** [comment]
I went directly to the Rust Foundation to get permission
Rest assured that all logos in this repository are officially licensed.
