### ISSUE TITLE
[Request] Charcoal

### ISSUE THREAD

**Issue by charlie5188** [SAWARATSUKI/KawaiiLogos#174]
### 重複チェック

- [X] 確認しました

### ロゴカテゴリ

service

### ロゴの名称

Charcoal

### ロゴの名称(日本語)

チャコール

### 許可の有無

Yes

### 連絡先

https://x.com/godling_zlm

### コメント・補足

Charcoalはピクシブのデザインシステムです：

- https://www.figma.com/@pixiv
- https://github.com/pixiv/charcoal

ロゴはトグルボタンみたいな、C文字みたいなものです。
![image](https://github.com/user-attachments/assets/d151374e-a554-4fc9-8adb-bbf305b055c4)

**Comment by charlie5188** [comment]
Skebで依頼は審査に通らなかったため、こちらで申請してみました

**Comment by SAWARATSUKI** [comment]
OK! I LOVE Pixiv!

**Comment by charlie5188** [comment]
ありがとうございます！

**Comment by SAWARATSUKI** [comment]
公開したためクローズ ✌️
