### ISSUE TITLE
[Request] VSCode

### ISSUE THREAD

**Issue by wastu01** [SAWARATSUKI/KawaiiLogos#75]
### 重複チェック

- [X] 確認しました

### ロゴカテゴリ

service

### ロゴの名称

VsCode, Logo

### ロゴの名称(日本語)

idk japanese

### 許可の有無

No

**Comment by nlxdodge** [comment]
I checked https://vtuber-style-logos.vercel.app/ and it seems he already made one, but hadn't uploaded it here yet.

![image](https://github.com/SAWARATSUKI/KawaiiLogos/assets/8994983/07d12c5e-eed6-48b1-b90c-6cca1f9b28d3)

**Comment by wastu01** [comment]
OK
