### ISSUE TITLE
READMEの表記の統一とアクセスの改善についての提案

### ISSUE THREAD

**Issue by smizuoch** [SAWARATSUKI/KawaiiLogos#77]
こんにちは。

現在、プロジェクトのREADMEファイルに関して、言語毎の表記が一貫性を欠いており、改善を提案したく思います。具体的には、英語版のREADMEが「言語 / Languages」セクションにリストされているのに対し、他の言語は「[言語] + README」という形で記載されています。この表記のばらつきが、情報の検索性を低下させ、利用者にとってわかりづらくなっていると感じています。

また、日本語のREADMEからのみ他言語のREADMEにアクセス可能という現状も、使用者にとって不便であると考えます。全ての言語のREADMEから互いにアクセスできるようにすることで、より多くのユーザーがスムーズに情報を得られるようになると思います。

これらの点について、表記を統一し、アクセス方法を改善することを提案します。ご検討のほどよろしくお願いいたします。

よろしくお願いします。

**Comment by xiaoqianWX** [comment]
PR #79 has fixed this
